//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormMainMenu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContactLensDoctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblContactLensDoctor()
        {
            this.tblContactLens = new HashSet<tblContactLens>();
        }
    
        public int ContactLensDoctorId { get; set; }
        public string ContactLensSerialNumber { get; set; }
        public string ContactLensOptometrist { get; set; }
        public string ContactLensOptician { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblContactLens> tblContactLens { get; set; }
    }
}
