//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormMainMenu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContactLens
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblContactLens()
        {
            this.tblPatientsContactLens = new HashSet<tblPatientsContactLens>();
        }
    
        public int ContactId { get; set; }
        public string SerialNumber { get; set; }
        public string ContactRS { get; set; }
        public string ContactRC { get; set; }
        public string ContactRA { get; set; }
        public string ContactRBC { get; set; }
        public string ContactRDptr { get; set; }
        public string ContactLS { get; set; }
        public string ContactLC { get; set; }
        public string ContactLA { get; set; }
        public string ContactLBC { get; set; }
        public string ContactLDptr { get; set; }
        public System.DateTime ContactDate { get; set; }
        public Nullable<int> ContactLensRemarksId { get; set; }
        public Nullable<int> ContactLensDoctorId { get; set; }
    
        public virtual tblContactLensRemarks tblContactLensRemark { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPatientsContactLens> tblPatientsContactLens { get; set; }
        public virtual tblContactLensDoctor tblContactLensDoctor { get; set; }
    }
}
