//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormMainMenu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOpticalLens
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOpticalLens()
        {
            this.tblPatientsOpticalLens = new HashSet<tblPatientsOpticalLens>();
        }
    
        public int OpticalId { get; set; }
        public string SerialNumber { get; set; }
        public string OpticalRS { get; set; }
        public string OpticalRC { get; set; }
        public string OpticalRA { get; set; }
        public string OpticalRPD { get; set; }
        public string OpticalRAdd { get; set; }
        public string OpticalRPrism { get; set; }
        public string OpticalRBase { get; set; }
        public string OpticalROH { get; set; }
        public string OpticalLS { get; set; }
        public string OpticalLC { get; set; }
        public string OpticalLA { get; set; }
        public string OpticalLPD { get; set; }
        public string OpticalLAdd { get; set; }
        public string OpticalLPrism { get; set; }
        public string OpticalLBase { get; set; }
        public string OpticalLOH { get; set; }
        public System.DateTime OpticalDate { get; set; }
        public Nullable<int> OpticalLensRemarksId { get; set; }
        public Nullable<int> OpticalLensDoctorId { get; set; }
    
        public virtual tblOpticalLensRemarks tblOpticalLensRemark { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPatientsOpticalLens> tblPatientsOpticalLens { get; set; }
        public virtual tblOpticalLensDoctor tblOpticalLensDoctor { get; set; }
    }
}
