//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormMainMenu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPatients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPatients()
        {
            this.tblPatientsContactLens = new HashSet<tblPatientsContactLens>();
            this.tblPatientsOpticalLens = new HashSet<tblPatientsOpticalLens>();
        }
    
        public int PatientId { get; set; }
        public string SerialNumber { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public byte Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public byte Age { get; set; }
        public string MobileNumber { get; set; }
        public string TelephoneNumber { get; set; }
        public string HouseNo { get; set; }
        public string Street { get; set; }
        public string Barangay { get; set; }
        public string City { get; set; }
        public System.DateTime PatientDate { get; set; }
        public string LastName { get; set; }
        public Nullable<byte> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPatientsContactLens> tblPatientsContactLens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPatientsOpticalLens> tblPatientsOpticalLens { get; set; }
    }
}
