//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormMainMenu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPatientsOpticalLens
    {
        public int PatientOpticalId { get; set; }
        public int PatientId { get; set; }
        public int OpticalId { get; set; }
    
        public virtual tblOpticalLens tblOpticalLen { get; set; }
        public virtual tblPatients tblPatient { get; set; }
    }
}
